name: CI workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache npm packages
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Format files
        run: npm run format

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}

      - name: Lint files
        run: npm run lint

      - name: Linting failed (attempting fix...)
        if: ${{ failure() }}
        run: npm run lint:fix

      - name: Commit fixed lint issues
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply fixed lint issues
          branch: ${{ github.head_ref }}

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache npm packages
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci
        env:
          CI: true
      
      - name: Run test suite
        run: npm run test
