name: Master Push

on:
  push:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run format

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}